### ISSUE TITLE
patch contains old change

### ISSUE THREAD

**Issue by WinterMute** [Oreo639/void-unsanitary-packages#1]
This part of the patch shouldn't be there https://github.com/Oreo639/void-unsanitary-packages/blob/master/templates/devkitpro-pacman/patches/devkitpro-mods.patch#L5-L22

That's a leftover from when I was attempting to get pacman to work properly without escalation but I ended up reverting the changes that allowed it. I've reverted this change in the devkitPro pacman repo now.

Also: thanks for bringing this to my attention even if it was inadvertently :P

**Comment by oreo639** [comment]
Thanks for pointing this out.

**Comment by oreo639** [comment]
https://github.com/Oreo639/void-unsanitary-packages/commit/7ace7fc1f2afe5078870c751b3b3a6e3f6dfa46f
This should be resolved now.
